services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_local_data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "54329:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: TuColmadoDb
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mongo_local_data:
  postgres_local_data:
