// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuColmadoRD.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TuColmadoRD.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TuColmadoDbContext))]
    [Migration("20260419203721_AddNcfAnnulmentLog")]
    partial class AddNcfAnnulmentLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Audit.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", "Audit");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Customers", "Customers");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CustomerAccounts", "Customers");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.DebtTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerAccountId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptReference")
                        .HasColumnType("text");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerAccountId1");

                    b.ToTable("DebtTransactions", "Customers");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FiscalReceipts", "Fiscal");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("integer");

                    b.Property<int>("EndSequence")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FiscalSequences", "Fiscal");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.NcfAnnulmentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnnulledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NcfAnnulmentLogs", "Fiscal");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("RatePercentage");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Taxes", "Fiscal");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.HumanResources.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees", "HumanResources");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.HumanResources.WorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("WorkShifts", "HumanResources");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "Inventory");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ItbisRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", "Inventory");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.UnitConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("FromUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FromUnitId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ToUnitId");

                    b.ToTable("UnitConversions", "Inventory");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.UnitOfMeasureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsFractionable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasures", "Inventory");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.ToTable("DeliveryOrders", "Logistics");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPersons", "Logistics");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseDetails", "Purchasing");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierNcf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders", "Purchasing");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", "Purchasing");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("ChangeDueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NcfNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalItbisAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sales", "Sales");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SaleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TaxAmount");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SaleDetails", "Sales");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisRateValue")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("LineItbisAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineSubtotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineTotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("QuantityValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", "Sales");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SaleId");

                    b.ToTable("SalePayments", "Sales");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualCashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashDifferenceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ClosingCashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExpectedCashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OpeningCashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAccountPayments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCardIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCashIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCashSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSalesCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalTransferIn")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId", "Status");

                    b.ToTable("Shifts", "Sales");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.System.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("ProcessedAt", "CreatedAt");

                    b.ToTable("OutboxMessages", "System");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.System.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigs", "System");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.System.TenantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TenantProfiles", "System");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("CashBoxes", "Treasury");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashDrawer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("CashDrawers", "Treasury");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashBoxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CashBoxId");

                    b.ToTable("Expenses", "Treasury");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.PettyCash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("PettyCashes", "Treasury");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Audit.AuditTrail", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("AuditTrailId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("AuditTrailId");

                            b1.ToTable("AuditTrails", "Audit");

                            b1.WithOwner()
                                .HasForeignKey("AuditTrailId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.Customer", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Phone", "ContactPhone", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Cedula", "DocumentId", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DocumentId");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Address_HouseNumber");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Province");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address_Reference");

                            b1.Property<string>("Sector")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Sector");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("ContactPhone");

                    b.Navigation("DocumentId");

                    b.Navigation("HomeAddress");

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("CustomerAccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("CustomerAccountId");

                            b1.ToTable("CustomerAccounts", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAccountId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "CreditLimit", b1 =>
                        {
                            b1.Property<Guid>("CustomerAccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CreditLimit");

                            b1.HasKey("CustomerAccountId");

                            b1.ToTable("CustomerAccounts", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAccountId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CustomerAccountId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CustomerAccountId");

                            b1.ToTable("CustomerAccounts", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAccountId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("CreditLimit")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.DebtTransaction", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerAccountId1");

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("DebtTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("DebtTransactionId");

                            b1.ToTable("DebtTransactions", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("DebtTransactionId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("DebtTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("DebtTransactionId");

                            b1.ToTable("DebtTransactions", "Customers");

                            b1.WithOwner()
                                .HasForeignKey("DebtTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalReceipt", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Rnc", "BuyerRnc", b1 =>
                        {
                            b1.Property<Guid>("FiscalReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("BuyerRnc");

                            b1.HasKey("FiscalReceiptId");

                            b1.ToTable("FiscalReceipts", "Fiscal");

                            b1.WithOwner()
                                .HasForeignKey("FiscalReceiptId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("FiscalReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("FiscalReceiptId");

                            b1.ToTable("FiscalReceipts", "Fiscal");

                            b1.WithOwner()
                                .HasForeignKey("FiscalReceiptId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TotalTaxed", b1 =>
                        {
                            b1.Property<Guid>("FiscalReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalTaxed");

                            b1.HasKey("FiscalReceiptId");

                            b1.ToTable("FiscalReceipts", "Fiscal");

                            b1.WithOwner()
                                .HasForeignKey("FiscalReceiptId");
                        });

                    b.Navigation("BuyerRnc");

                    b.Navigation("TenantId")
                        .IsRequired();

                    b.Navigation("TotalTaxed")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalSequence", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("FiscalSequenceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("FiscalSequenceId");

                            b1.ToTable("FiscalSequences", "Fiscal");

                            b1.WithOwner()
                                .HasForeignKey("FiscalSequenceId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.NcfAnnulmentLog", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("NcfAnnulmentLogId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("NcfAnnulmentLogId");

                            b1.ToTable("NcfAnnulmentLogs", "Fiscal");

                            b1.WithOwner()
                                .HasForeignKey("NcfAnnulmentLogId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.Tax", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("TaxId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("TaxId");

                            b1.ToTable("Taxes", "Fiscal");

                            b1.WithOwner()
                                .HasForeignKey("TaxId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.HumanResources.Employee", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Cedula", "IdCard", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("IdCard");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees", "HumanResources");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees", "HumanResources");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees", "HumanResources");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("IdCard");

                    b.Navigation("Phone");

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.HumanResources.WorkShift", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("WorkShiftId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("WorkShiftId");

                            b1.ToTable("WorkShifts", "HumanResources");

                            b1.WithOwner()
                                .HasForeignKey("WorkShiftId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Category", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories", "Inventory");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Product", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", "Inventory");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.UnitConversion", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.UnitOfMeasureEntity", "FromUnit")
                        .WithMany()
                        .HasForeignKey("FromUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.UnitOfMeasureEntity", "ToUnit")
                        .WithMany()
                        .HasForeignKey("ToUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("UnitConversionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("UnitConversionId");

                            b1.ToTable("UnitConversions", "Inventory");

                            b1.WithOwner()
                                .HasForeignKey("UnitConversionId");
                        });

                    b.Navigation("FromUnit");

                    b.Navigation("TenantId")
                        .IsRequired();

                    b.Navigation("ToUnit");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryOrder", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryPerson", null)
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Address", "Destination", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Destination_HouseNumber");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Destination_Province");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Destination_Reference");

                            b1.Property<string>("Sector")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Destination_Sector");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Destination_Street");

                            b1.HasKey("DeliveryOrderId");

                            b1.ToTable("DeliveryOrders", "Logistics");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOrderId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("DeliveryOrderId");

                            b1.ToTable("DeliveryOrders", "Logistics");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOrderId");
                        });

                    b.Navigation("Destination")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryPerson", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Phone", "ContactPhone", b1 =>
                        {
                            b1.Property<Guid>("DeliveryPersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons", "Logistics");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("DeliveryPersonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons", "Logistics");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.Navigation("ContactPhone");

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseDetail", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", null)
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Purchasing.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders", "Purchasing");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.Supplier", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Rnc", "Rnc", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("Rnc");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers", "Purchasing");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers", "Purchasing");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("Rnc")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Sale", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales", "Sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SaleDetail", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SaleItem", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Sales.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SalePayment", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Sales.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Shift", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts", "Sales");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.System.TenantProfile", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Rnc", "Rnc", b1 =>
                        {
                            b1.Property<Guid>("TenantProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("Rnc");

                            b1.HasKey("TenantProfileId");

                            b1.ToTable("TenantProfiles", "System");

                            b1.WithOwner()
                                .HasForeignKey("TenantProfileId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("TenantProfileId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("TenantProfileId");

                            b1.ToTable("TenantProfiles", "System");

                            b1.WithOwner()
                                .HasForeignKey("TenantProfileId");
                        });

                    b.Navigation("Rnc");

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashBox", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("CashBoxId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("CashBoxId");

                            b1.ToTable("CashBoxes", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("CashBoxId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CashBoxId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CashBoxId");

                            b1.ToTable("CashBoxes", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("CashBoxId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashDrawer", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Sales.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "CurrentBalance", b1 =>
                        {
                            b1.Property<Guid>("CashDrawerId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CurrentBalance");

                            b1.HasKey("CashDrawerId");

                            b1.ToTable("CashDrawers", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("CashDrawerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "OpeningBalance", b1 =>
                        {
                            b1.Property<Guid>("CashDrawerId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("OpeningBalance");

                            b1.HasKey("CashDrawerId");

                            b1.ToTable("CashDrawers", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("CashDrawerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CashDrawerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CashDrawerId");

                            b1.ToTable("CashDrawers", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("CashDrawerId");
                        });

                    b.Navigation("CurrentBalance")
                        .IsRequired();

                    b.Navigation("OpeningBalance")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.Expense", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Treasury.CashBox", null)
                        .WithMany()
                        .HasForeignKey("CashBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.PettyCash", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("PettyCashId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("PettyCashId");

                            b1.ToTable("PettyCashes", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("PettyCashId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "MaxLimit", b1 =>
                        {
                            b1.Property<Guid>("PettyCashId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MaxLimit");

                            b1.HasKey("PettyCashId");

                            b1.ToTable("PettyCashes", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("PettyCashId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("PettyCashId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("PettyCashId");

                            b1.ToTable("PettyCashes", "Treasury");

                            b1.WithOwner()
                                .HasForeignKey("PettyCashId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("MaxLimit")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Sale", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
